# Uncomment the next line to define a global platform for your project
# platform :ios, '12.0'

target 'DubizzleChallange' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for DubizzleChallange
  pod 'SVProgressHUD'
  pod 'SCLAlertView'
  pod 'SDWebImage'
  pod 'UIScrollView-InfiniteScroll'
  pod 'SwiftMessageBar'
  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'
  pod 'PopupDialog', '~> 1.1'
  pod 'RxDataSources', '~> 4.0'

end
